spring:
  profiles:
    active: dev
  application:
    name: product-service
  cloud:
    config:
      uri: http://localhost:8888/
      label: dev/Behzod
  config:
    import: optional:configserver:http://localhost:8888/